name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Build no_std
        run: cargo build --no-default-features

  msrv-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install MSRV
        run: rustup update 1.62.1 && rustup default 1.62.1
      - name: Test
        run: cargo test --verbose
      - name: Build no_std
        run: cargo build --no-default-features
